# Generated by Django 5.0.1 on 2024-01-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('temperature', models.FloatField()),
                ('apparent_temperature', models.FloatField()),
                ('precipitation', models.FloatField()),
                ('rain', models.FloatField()),
                ('snowfall', models.FloatField()),
                ('cloud_cover', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('wind_direction', models.FloatField()),
                ('humidity', models.FloatField()),
                ('description', models.IntegerField()),
            ],
        ),
    ]
